from typing import Protocol, runtime_checkable
from pygame.surface import Surface
from pygame.event import Event


@runtime_checkable
class SceneProtocol(Protocol):
    def start(self) -> None: ...

    def quit(self) -> None: ...

    @property
    def running(self) -> bool: ...

    def handle_event(self, event: Event) -> None: ...

    def update(self, dt_s: float) -> None: ...

    def draw(self, screen: Surface) -> None: ...

    def decide(self) -> type[SceneProtocol]: ...
